### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by Jahongir-Qurbonov** [LonamiWebs/Telethon#4482]
### Describe your suggested feature

V2 is great and the community is waiting for its stable version. We are willing to contribute if there is work to be done for a stable version.

Todos:

- [ ] Add QR code authorization
- [ ] Networking needs to be reconsidered
- [ ] Message entity parsing should be improved

**Comment by Lonami** [comment]
My plan for v2 was primarily to redesign the core of the library based on what I had learnt from making grammers, and use proper types.

As for the high-level API, my plan was to take what was most used from v1, and remove anything that didn't pull its own weight. This includes conversations and all ugly hacks used by custom types.

Honestly, v2 is probably not missing that much, but I'm sure it's also nowhere as stable as v1, network-wise. Another pain point is Markdown. CommonMark just doesn't cut it, as Telegram has many more formatting entities. This affects big part of the library and we need a better solution. We might just need to copy what the HTTP Bot API is doing for formatting.

**Comment by Jahongir-Qurbonov** [comment]
When can you review the network-wise? Better to copy Markdown from HTTP bot api in my opinion

**Comment by Lonami** [comment]
> When can you review the network-wise?

Not sure. Telethon v1's network stack matured this much over time, and I suspect something similar will happen with v2.

> Better to copy Markdown from HTTP bot api in my opinion

I'm hesitant. People might expect compatibility, which I'd rather not promise to maintain.

But, it's probably the best bet.

**Comment by Heshmatkhah** [comment]
Hi,
Thank you for your grate work.

Is v2 ready for production use?


> People might expect compatibility

It's a major version update, do whatever you need to!

Thank you

**Comment by Lonami** [comment]
> Is v2 ready for production use?

No, and I unfortunately do not know when it will be.

**Comment by MrSnowball-dev** [comment]
As a longtime Telethon user, I am all for following HTTP Bot API way for Markdown, as it is the most documented, easily followed and a way that Telegram expects it to be. Whoever expects compatibility would update their code anyway, converting from V1 to V2.

The maintaining though can not be very difficult, as new formatting entities are not really being added anymore, and if it does it's like once in a few years.

**Comment by Lonami** [comment]
Closing as there's no longer a plan, to be realistic. I'll probably end up figuring something on the fly, if v2 ever happens.
